const CHECK_FIRST_TIME = "CHECK_FIRST_TIME";
const SET_FIRST_TIME = "SET_FIRST_TIME";
const LOAD_GOALS = "LOAD_GOALS";
const ADD_GOAL = "ADD_GOAL";
const DELETE_GOAL = "DELETE_GOAL";
const EDIT_GOAL = "EDIT_GOAL";
const CHECK_GOAL = "CHECK_GOAL";
const SET_CURRENT_GOAL = "SET_CURRENT_GOAL";

export {
    CHECK_FIRST_TIME,
    SET_FIRST_TIME,
    LOAD_GOALS,
    ADD_GOAL,
    DELETE_GOAL,
    EDIT_GOAL,
    CHECK_GOAL,
    SET_CURRENT_GOAL,
};
